spring.application.name=gateway

server.port=8080

# =========================
# DONACIONES
# =========================

spring.cloud.gateway.server.webflux.routes[0].id=donaciones
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/donaciones/**

spring.cloud.gateway.server.webflux.routes[0].filters[0].name=RewritePath
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.regexp=/donaciones/(?<segment>.*)
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.replacement=/${segment}

spring.cloud.gateway.server.webflux.routes[0].filters[1].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.name=donacionesCircuit
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.fallbackUri=forward:/fallback/donaciones


# =========================
# INVENTARIO
# =========================

spring.cloud.gateway.server.webflux.routes[1].id=inventario
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/inventario/**

spring.cloud.gateway.server.webflux.routes[1].filters[0].name=RewritePath
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.regexp=/inventario/(?<segment>.*)
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.replacement=/${segment}

spring.cloud.gateway.server.webflux.routes[1].filters[1].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.name=inventarioCircuit
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.fallbackUri=forward:/fallback/inventario


# =========================
# LOGISTICA
# =========================

spring.cloud.gateway.server.webflux.routes[2].id=logistica
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/logistica/**

spring.cloud.gateway.server.webflux.routes[2].filters[0].name=RewritePath
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.regexp=/logistica/(?<segment>.*)
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.replacement=/${segment}

spring.cloud.gateway.server.webflux.routes[2].filters[1].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[2].filters[1].args.name=logisticaCircuit
spring.cloud.gateway.server.webflux.routes[2].filters[1].args.fallbackUri=forward:/fallback/logistica