spring.application.name=gateway

server.port=8080

# =========================
# DONACIONES
# =========================

spring.cloud.gateway.server.webflux.routes[0].id=donaciones
spring.cloud.gateway.server.webflux.routes[0].uri=${DONACIONES_URI:http://localhost:8081}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/donaciones/**



# =========================
# INVENTARIO
# =========================

spring.cloud.gateway.server.webflux.routes[1].id=inventario
spring.cloud.gateway.server.webflux.routes[1].uri=${INVENTARIO_URI:http://localhost:8082}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/inventario/**



# =========================
# LOGISTICA
# =========================

spring.cloud.gateway.server.webflux.routes[2].id=logistica
spring.cloud.gateway.server.webflux.routes[2].uri=${LOGISTICA_URI:http://localhost:8083}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/logistica/**



# =========================
# AUTH
# =========================

spring.cloud.gateway.server.webflux.routes[3].id=auth
spring.cloud.gateway.server.webflux.routes[3].uri=${AUTH_URI:http://localhost:8084}
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/auth/**,/api/usuarios/**


# =========================
# NECESIDADES
# =========================

spring.cloud.gateway.server.webflux.routes[4].id=necesidades
spring.cloud.gateway.server.webflux.routes[4].uri=${NECESIDADES_URI:http://localhost:8085}
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/necesidades/**