spring.application.name=donaciones

server.port=8081

spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/donaton
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
