version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: postgres_donaton
    environment:
      POSTGRES_DB: donaton
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"

  donaciones:
    build: .
    container_name: donaciones_app
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/donaton
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123