spring.application.name=authservice
server.port=8084

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/humanitarian_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=${JWT_SECRET:esta_es_una_clave_secreta_muy_larga_y_segura_dev_only_123456}